### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by boblannon** [pgbovine/json-summarizer#2]
This is such a handy utility for ETL QA, thank you!  Have you thought about adding a license to it? Doing so would make contributing a bit more attractive (at least for me).

Either way, thanks! :)

**Comment by pgbovine** [comment]
done!

**Comment by nealmcb** [comment]
Thanks!

For the record, this was closed by adding MIT license in https://github.com/pgbovine/json-summarizer/commit/e4e930c58d1ee0157b01a1229b1c79d1fa4018eb
